// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtdtOi4_HUm86F_dYIeu4VfkdqEntohr8',
    appId: '1:878854246610:web:727e76fa51c7caf18c9d0b',
    messagingSenderId: '878854246610',
    projectId: 'calm-space-771b4',
    authDomain: 'calm-space-771b4.firebaseapp.com',
    storageBucket: 'calm-space-771b4.appspot.com',
    measurementId: 'G-EL0L8WEVQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbuXS0RUOjY2avcSSO7PB6AIrx3deYdMM',
    appId: '1:878854246610:android:3994fd28a29b63738c9d0b',
    messagingSenderId: '878854246610',
    projectId: 'calm-space-771b4',
    storageBucket: 'calm-space-771b4.appspot.com',
  );

}